### ISSUE TITLE
Database page is down

### ISSUE THREAD

**Issue by oak-tree** [monocle-h2020/camera_calibration#1]
Hey, any chance to access the database of spectral sensitivity of each sensor?
Thanks1

**Comment by burggraaff** [comment]
Thanks for letting me know about the outage! I will look into it and leave a comment when this is sorted.

**Comment by yoavhalevi** [comment]
Hey @burggraaff ,

Any news?
Is there a temporal solution that you can provide in the meantime?

Thanks in advance

**Comment by burggraaff** [comment]
@yoavhalevi Send me an email at burggraaff@strw.leidenuniv.nl and I will email you the data :)

**Comment by yoavhalevi** [comment]
@burggraaff Thanks!
I have sent you an email, I wonder if you got it...

**Comment by burggraaff** [comment]
The data are available from this folder for now:
https://drive.google.com/drive/folders/1acKQBolfL1gsyeGRGuOHT8UDONjBTdhU?usp=sharing
