### ISSUE TITLE
camera calibration

### ISSUE THREAD

**Issue by mingao9618** [monocle-h2020/camera_calibration#2]
Hello, I am a doctoral student, and I am studying the inversion of water reflectance using the original format of the camera. I saw your article “Standardized spectral and radiometric
calibration of consumer cameras”, and the program you uploaded on GitHub to read the original format photos of the camera. I also tried to use your program to read the original format photos of the Canon 50D camera, but encountered difficulties, I can't find the json file, So emailed to ask you. I would be very grateful if you could help me.

**Comment by burggraaff** [comment]
This issue has been resolved over email.

**Comment by mingao9618** [comment]
Sorry, the raw file is too large to send to you.
I wonder if you have any other methods that I could send raw files to you.


从 Windows 版邮件发送

发件人: Olivier Burggraaff
发送时间: 2022年4月24日 23:29
收件人: monocle-h2020/camera_calibration
抄送: mingao9618; Author
主题: Re: [monocle-h2020/camera_calibration] camera calibration (Issue #2)

Closed #2.
